import { StyleSheet, Platform } from 'react-native';

const SIDEBAR_WIDTH = 260;

const styles = StyleSheet.create({
  root: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: '#fff',
  },
  sidebar: {
    width: SIDEBAR_WIDTH,
    backgroundColor: '#f3f3f3',
    borderRightWidth: 1,
    borderRightColor: '#e0e0e0',
    paddingTop: 0,
    paddingHorizontal: 0,
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    zIndex: 20,
    elevation: 10,
    shadowColor: '#000',
    shadowOffset: { width: 1, height: 0 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
  },
  menuContainer: {
    flex: 1,
    paddingTop: 60,
    paddingHorizontal: 24,
  },
  menuTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 24,
    color: '#222',
  },
  menuItem: {
    paddingVertical: 12,
    paddingHorizontal: 0,
    borderRadius: 6,
    marginBottom: 8,
    backgroundColor: '#e8f5e9',
  },
  menuItemText: {
    fontSize: 16,
    color: '#222',
    fontWeight: '500',
  },
  burgerBtn: {
    position: 'absolute',
    left: 18,
    top: 36,
    zIndex: 30,
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.9)',
    borderRadius: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 2,
    elevation: 2,
  },
  burgerBar: {
    width: 22,
    height: 3,
    backgroundColor: '#222',
    borderRadius: 2,
    marginVertical: 2,
  },
  drawerOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.18)',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
  },
  drawerContent: {
    width: SIDEBAR_WIDTH,
    backgroundColor: '#f3f3f3',
    height: '100%',
    paddingTop: 0,
    paddingHorizontal: 0,
    borderRightWidth: 1,
    borderRightColor: '#e0e0e0',
    elevation: 12,
    shadowColor: '#000',
    shadowOffset: { width: 1, height: 0 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
  },
  container: {
    flex: 1,
    backgroundColor: '#fff',
    paddingTop: 60,
    paddingHorizontal: 20,
  },
  title: {
    fontSize: 28,
    fontWeight: 'bold',
    marginBottom: 20,
    alignSelf: 'center',
    color: '#222',
  },
  list: {
    flex: 1,
  },
  todoItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f5f5f5',
    borderRadius: 8,
    padding: 12,
    marginBottom: 10,
  },
  checkbox: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#bbb',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  todoText: {
    fontSize: 16,
    color: '#222',
  },
  todoDone: {
    textDecorationLine: 'line-through',
    color: '#bbb',
  },
  deleteBtn: {
    marginLeft: 10,
    padding: 4,
  },
  fab: {
    position: 'absolute',
    right: 24,
    bottom: 32,
    backgroundColor: '#4caf50',
    width: 60,
    height: 60,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 5,
    zIndex: 10,
  },
  fabIcon: {
    color: '#fff',
    fontSize: 36,
    fontWeight: 'bold',
    marginTop: -2,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.25)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 28,
    minWidth: 320,
    maxWidth: 400,
    width: '90%',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 8,
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    marginBottom: 18,
    color: '#222',
  },
  modalInput: {
    width: '100%',
    minHeight: 60,
    maxHeight: 120,
    fontSize: 20,
    borderColor: '#eee',
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 16,
    paddingVertical: 12,
    marginBottom: 20,
    backgroundColor: '#fafafa',
    color: '#222',
    textAlignVertical: 'top',
  },
  modalActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    width: '100%',
  },
  modalBtn: {
    backgroundColor: '#4caf50',
    borderRadius: 8,
    paddingHorizontal: 24,
    paddingVertical: 10,
    marginLeft: 10,
    alignItems: 'center',
  },
  modalBtnText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
  },
});

export default styles; 